[db]
db_flavour = "POSTGRES"
host = "10.20.254.226"
port = 5432
user = "gengsu07"
password = "Gengsu!sh3r3"
schema = "public"
database = "ppmpkm"

[filters]
MAP=['Bea Meterai','Pajak Penjualan Batubara','Pajak Tidak Langsung','PBB Sektor Lainnya','PBB Sektor Migas','Penjualan Benda Meterai','PPh 21','PPh 22','PPh 22 Impor','PPh 23','PPh 25 Badan','PPh 25 OP','PPh 25 OP DTP','PPh 26','PPh Final','PPh Final DTP','PPh Gas Alam','PPh Migas Lainnya','PPh Minyak Bumi','PPh Non Migas Lainnya','PPh Pasal 21 DTP','PPh Pasal 25/29 Badan DTP','PPnBM DN','PPnBM Impor','PPnBM Lainnya','PPN DN','PPN DTP','PPN Impor','PPN Lainnya','STP atas Bunga Penagihan','STP atas Bunga Penagihan PPN']
NM_KATEGORI = ['ADMINISTRASI PEMERINTAHAN, PERTAHANAN DAN JAMINAN SOSIAL WAJIB','AKTIVITAS JASA LAINNYA','AKTIVITAS KESEHATAN MANUSIA DAN AKTIVITAS SOSIAL','AKTIVITAS KEUANGAN DAN ASURANSI','AKTIVITAS PENYEWAAN DAN SEWA GUNA USAHA TANPA HAK OPSI, KETENAGAKERJAAN, AGEN PERJALANAN DAN PENUNJANG USAHA LAINNYA','AKTIVITAS PROFESIONAL, ILMIAH DAN TEKNIS','AKTIVITAS RUMAH TANGGA SEBAGAI PEMBERI KERJA; AKTIVITAS YANG MENGHASILKAN BARANG DAN JASA OLEH RUMAH TANGGA YANG DIGUNAKAN UNTUK MEMENUHI KEBUTUHAN SENDIRI','INDUSTRI PENGOLAHAN','INFORMASI DAN KOMUNIKASI','KESENIAN, HIBURAN DAN REKREASI','KONSTRUKSI','PEJABAT NEGARA, KARYAWAN, PENSIUNAN, TIDAK/BELUM BEKERJA','PENDIDIKAN','PENGADAAN LISTRIK, GAS, UAP/AIR PANAS DAN UDARA DINGIN','PENGANGKUTAN DAN PERGUDANGAN','PENYEDIAAN AKOMODASI DAN PENYEDIAAN MAKAN MINUM','PERDAGANGAN BESAR DAN ECERAN; REPARASI DAN PERAWATAN MOBIL DAN SEPEDA MOTOR','PERTAMBANGAN DAN PENGGALIAN','PERTANIAN, KEHUTANAN DAN PERIKANAN','REAL ESTAT','TREATMENT AIR, TREATMENT AIR LIMBAH, TREATMENT DAN PEMULIHAN MATERIAL SAMPAH, DAN AKTIVITAS REMEDIASI']
KDBAYAR = ['100','101','102','103','104','105','106','107','108','121','122','199','200','201','202','204','205','206','300','301','310','311','312','313','320','321','390','401','402','403','404','405','407','408','409','410','411','413','414','415','416','417','418','419','420','421','422','423','424','427','428','499','500','501','510','511','512','514','900','901','902','910','920','930']
KET = ['MPN','PBK KIRIM','PBK TERIMA','SPM','SPMKP']
DATEBAYAR=[2021,2024]
ADMIN=['001','002','003','004','005','007','008','009','097']
JENIS_WP=['BADAN','OP','PEMUNGUT']
SEGMENTASI_WP=['Strategis','Kewilayahan']

[filters_types]
MAP='string'
NM_KATEGORI='string'
KDBAYAR='string'
KET='string'
DATEBAYAR='datetime'
ADMIN='string'
JENIS_WP='string'
SEGMENTASI_WP='string'